// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByFHM2Fza_1hx9S0OWIVuAV-w_aheTIUw',
    appId: '1:988416876830:web:aca2db88e0b22710eae90f',
    messagingSenderId: '988416876830',
    projectId: 'kutbi-store',
    authDomain: 'kutbi-store.firebaseapp.com',
    storageBucket: 'kutbi-store.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrwOGAO6P5uP2lzDkgm3GEkcp7QfdTxyk',
    appId: '1:988416876830:android:ea6e9ec9aa843250eae90f',
    messagingSenderId: '988416876830',
    projectId: 'kutbi-store',
    storageBucket: 'kutbi-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1P9T1mJHJJPpqvn5Lq1aJz1HjCCOjU2U',
    appId: '1:988416876830:ios:824da171d0a3de92eae90f',
    messagingSenderId: '988416876830',
    projectId: 'kutbi-store',
    storageBucket: 'kutbi-store.firebasestorage.app',
    iosBundleId: 'com.linkdev.kutbi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1P9T1mJHJJPpqvn5Lq1aJz1HjCCOjU2U',
    appId: '1:988416876830:ios:824da171d0a3de92eae90f',
    messagingSenderId: '988416876830',
    projectId: 'kutbi-store',
    storageBucket: 'kutbi-store.firebasestorage.app',
    iosBundleId: 'com.linkdev.kutbi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByFHM2Fza_1hx9S0OWIVuAV-w_aheTIUw',
    appId: '1:988416876830:web:177774437fd48a7beae90f',
    messagingSenderId: '988416876830',
    projectId: 'kutbi-store',
    authDomain: 'kutbi-store.firebaseapp.com',
    storageBucket: 'kutbi-store.firebasestorage.app',
  );
}
